# Generated by Django 5.2.8 on 2025-11-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('deposit_number', models.CharField(db_column='Deposit_Number', max_length=6, primary_key=True, serialize=False)),
                ('isolation_date', models.TextField(blank=True, db_column='Isolation_Date', null=True)),
                ('isolator', models.TextField(blank=True, db_column='Isolator', null=True)),
                ('original_strain_number', models.TextField(blank=True, db_column='Original_Strain_Number', null=True)),
                ('closest_species', models.TextField(blank=True, db_column='Closest_Species', null=True)),
                ('similarity_percentage', models.FloatField(blank=True, db_column='Similarity_Percentage', null=True)),
                ('number_16s', models.TextField(blank=True, db_column='16S', null=True)),
                ('length', models.BigIntegerField(blank=True, db_column='Length', null=True)),
                ('accession', models.TextField(blank=True, db_column='Accession', null=True)),
                ('taxonomic_unit', models.TextField(blank=True, db_column='Taxonomic_Unit', null=True)),
                ('isolation_source', models.TextField(blank=True, db_column='Isolation_Source', null=True)),
                ('sample_collection_time', models.TextField(blank=True, db_column='Sample_Collection_Time', null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('age', models.FloatField(blank=True, db_column='Age', null=True)),
                ('health_status', models.TextField(blank=True, db_column='Health_Status', null=True)),
                ('living_area', models.TextField(blank=True, db_column='Living_Area', null=True)),
                ('bmi', models.FloatField(blank=True, db_column='BMI', null=True)),
                ('isolation_medium', models.TextField(blank=True, db_column='Isolation_Medium', null=True)),
                ('identification_medium', models.TextField(blank=True, db_column='Identification_Medium', null=True)),
                ('culture_temperature', models.BigIntegerField(blank=True, db_column='Culture_Temperature', null=True)),
                ('recommended_culture_time', models.BigIntegerField(blank=True, db_column='Recommended_Culture_Time', null=True)),
                ('aerobicity', models.TextField(blank=True, db_column='Aerobicity', null=True)),
                ('receipt_date', models.TextField(blank=True, db_column='Receipt_Date', null=True)),
                ('slant_photo', models.TextField(blank=True, db_column='Slant_Photo', null=True)),
                ('liquid_photo', models.TextField(blank=True, db_column='Liquid_Photo', null=True)),
                ('slant_storage', models.BigIntegerField(blank=True, db_column='Slant_Storage', null=True)),
                ('glycerol_preservation', models.BigIntegerField(blank=True, db_column='Glycerol_Preservation', null=True)),
                ('lyophilization_preservation', models.BigIntegerField(blank=True, db_column='Lyophilization_Preservation', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('metabolomics_data', models.TextField(blank=True, db_column='Metabolomics_Data', null=True)),
                ('Genomic_Information', models.TextField(blank=True, db_column='Genomic_Information', null=True)),
            ],
            options={
                'db_table': 'test1',
                'managed': True,
            },
        ),
    ]
