# Generated by Django 3.2.25 on 2025-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='liquid_photo',
            field=models.CharField(blank=True, db_column='Liquid_Photo', max_length=255, null=True, verbose_name='液体图片路径'),
        ),
        migrations.AlterField(
            model_name='test1',
            name='slant_photo',
            field=models.CharField(blank=True, db_column='Slant_Photo', max_length=255, null=True, verbose_name='倾斜图片路径'),
        ),
    ]
