# Generated by Django 3.2 on 2025-10-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('deposit_number', models.TextField(blank=True, db_column='Deposit_Number', primary_key=True, serialize=False)),
                ('isolation_date', models.TextField(blank=True, db_column='Isolation_Date', null=True)),
                ('isolator', models.TextField(blank=True, db_column='Isolator', null=True)),
                ('original_strain_number', models.TextField(blank=True, db_column='Original_Strain_Number', null=True)),
                ('closest_species', models.TextField(blank=True, db_column='Closest_Species', null=True)),
                ('similarity_percentage', models.FloatField(blank=True, db_column='Similarity_Percentage', null=True)),
                ('number_16s', models.TextField(blank=True, db_column='16S', null=True)),
                ('length', models.BigIntegerField(blank=True, db_column='Length', null=True)),
                ('accession', models.TextField(blank=True, db_column='Accession', null=True)),
                ('taxonomic_unit', models.TextField(blank=True, db_column='Taxonomic_Unit', null=True)),
                ('isolation_source', models.TextField(blank=True, db_column='Isolation_Source', null=True)),
                ('sample_collection_time', models.TextField(blank=True, db_column='Sample_Collection_Time', null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('age', models.FloatField(blank=True, db_column='Age', null=True)),
                ('health_status', models.TextField(blank=True, db_column='Health_Status', null=True)),
                ('living_area', models.TextField(blank=True, db_column='Living_Area', null=True)),
                ('bmi', models.FloatField(blank=True, db_column='BMI', null=True)),
                ('isolation_medium', models.TextField(blank=True, db_column='Isolation_Medium', null=True)),
                ('identification_medium', models.TextField(blank=True, db_column='Identification_Medium', null=True)),
                ('culture_temperature', models.BigIntegerField(blank=True, db_column='Culture_Temperature', null=True)),
                ('recommended_culture_time', models.BigIntegerField(blank=True, db_column='Recommended_Culture_Time', null=True)),
                ('aerobicity', models.TextField(blank=True, db_column='Aerobicity', null=True)),
                ('receipt_date', models.TextField(blank=True, db_column='Receipt_Date', null=True)),
                ('slant_photo', models.TextField(blank=True, db_column='Slant_Photo', null=True)),
                ('liquid_photo', models.TextField(blank=True, db_column='Liquid_Photo', null=True)),
                ('slant_storage', models.BigIntegerField(blank=True, db_column='Slant_Storage', null=True)),
                ('glycerol_preservation', models.BigIntegerField(blank=True, db_column='Glycerol_Preservation', null=True)),
                ('lyophilization_preservation', models.BigIntegerField(blank=True, db_column='Lyophilization_Preservation', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'test1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueraDataCustomuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'quera_data_customuser',
                'managed': True,
            },
        ),
    ]
