# Generated by Django 3.2 on 2025-10-19 00:57

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueraDataCustomuser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'quera_data_customuser',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('deposit_number', models.TextField(blank=True, db_column='Deposit_Number', primary_key=True, serialize=False)),
                ('isolation_date', models.TextField(blank=True, db_column='Isolation_Date', null=True)),
                ('isolator', models.TextField(blank=True, db_column='Isolator', null=True)),
                ('original_strain_number', models.TextField(blank=True, db_column='Original_Strain_Number', null=True)),
                ('closest_species', models.TextField(blank=True, db_column='Closest_Species', null=True)),
                ('similarity_percentage', models.FloatField(blank=True, db_column='Similarity_Percentage', null=True)),
                ('number_16s', models.TextField(blank=True, db_column='16S', null=True)),
                ('length', models.BigIntegerField(blank=True, db_column='Length', null=True)),
                ('accession', models.TextField(blank=True, db_column='Accession', null=True)),
                ('taxonomic_unit', models.TextField(blank=True, db_column='Taxonomic_Unit', null=True)),
                ('isolation_source', models.TextField(blank=True, db_column='Isolation_Source', null=True)),
                ('sample_collection_time', models.TextField(blank=True, db_column='Sample_Collection_Time', null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('age', models.FloatField(blank=True, db_column='Age', null=True)),
                ('health_status', models.TextField(blank=True, db_column='Health_Status', null=True)),
                ('living_area', models.TextField(blank=True, db_column='Living_Area', null=True)),
                ('bmi', models.FloatField(blank=True, db_column='BMI', null=True)),
                ('isolation_medium', models.TextField(blank=True, db_column='Isolation_Medium', null=True)),
                ('identification_medium', models.TextField(blank=True, db_column='Identification_Medium', null=True)),
                ('culture_temperature', models.BigIntegerField(blank=True, db_column='Culture_Temperature', null=True)),
                ('recommended_culture_time', models.BigIntegerField(blank=True, db_column='Recommended_Culture_Time', null=True)),
                ('aerobicity', models.TextField(blank=True, db_column='Aerobicity', null=True)),
                ('receipt_date', models.TextField(blank=True, db_column='Receipt_Date', null=True)),
                ('slant_photo', models.TextField(blank=True, db_column='Slant_Photo', null=True)),
                ('liquid_photo', models.TextField(blank=True, db_column='Liquid_Photo', null=True)),
                ('slant_storage', models.BigIntegerField(blank=True, db_column='Slant_Storage', null=True)),
                ('glycerol_preservation', models.BigIntegerField(blank=True, db_column='Glycerol_Preservation', null=True)),
                ('lyophilization_preservation', models.BigIntegerField(blank=True, db_column='Lyophilization_Preservation', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'test1',
                'managed': False,
            },
        ),
    ]
