# Generated by Django 3.2 on 2025-11-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('state', models.CharField(max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='queradatacustomuser',
            options={'managed': False},
        ),
    ]
